config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tweets/result' => 'tweets#result'
  get 'tweets/music' => 'tweets#music'
  get 'tweets/cooking' => 'tweets#cooking'
  get 'tweets/anime' => 'tweets#anime'
  resources :users, only: [:show] # ユーザーマイページへのルーティング

  resources :perfumes

  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  
 
  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/perfume.rb
class Perfume < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord

  validates :name, presence: true
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy

end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader

    #tweetsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy
  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記
  
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    
end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
    def index
    end
  
    def new
      @perfume = Perfume.new
    end
  
    def show
      @perfume = Perfume.find_by(id: params[:id])
    end
  
    def create
      @perfume = Perfume.new(perfume_params)
      params[:perfume][:question] ? @perfume.question = params[:perfume][:question].join("") : false
      if @perfume.save
          flash[:notice] = "診断が完了しました"
          redirect_to perfume_path(@perfume.id)
      else
          redirect_to :action => "new"
      end
    end
  
  private
    def perfume_params
        params.require(:perfume).permit(:id, question: [])
    end
end
  

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]

    def index
        @tweets = Tweet.all
        if params[:tag_ids]
            @tweets = []
            params[:tag_ids].each do |key, value|      
              @tweets += Tag.find_by(name: key).tweets if value == "1"
            end
            @tweets.uniq!
        end
    end

    

    def new
        @tweet = Tweet.new
      end
    
      def create
        tweet = Tweet.new(tweet_params)

        tweet.user_id = current_user.id

        if tweet.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @tweet = Tweet.find(params[:id])
        @comments = @tweet.comments
        @comment = Comment.new
      end
      
      def edit
        @tweet = Tweet.find(params[:id])
      end

      def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
          redirect_to :action => "index", :id => tweet.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to session[:previous_url]
      end

      def result
        @tweets=Tweet.where(genre: "スポーツ")
        session[:previous_url] = request.referer
      end
    
      def music
        @tweets=Tweet.where(genre: "音楽")
        session[:previous_url] = request.referer
      end

      def cooking
        @tweets=Tweet.where(genre: "料理")
        session[:previous_url] = request.referer
      end

      def anime
        @tweets=Tweet.where(genre: "漫画・アニメ")
        session[:previous_url] = request.referer
      end

      private
      def tweet_params
        params.require(:tweet).permit(:about, :genre, :image, tag_ids: [])

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
     @user = User.find(params[:id]) 
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<header>
  <div class="header-logo">
    <h1></h1>
  </div>
  <div class="openbtn"><span></span><span></span><span></span></div>
  <nav id="g-nav">
    <div id="g-nav-list">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p" rel="stylesheet">
      <ul>
        <li>
        <%= link_to "Top", tweets_path %>
        </li>
        <li>
        <%= link_to "NEW POST", new_tweet_path %>
        </li>
        <li>
        <%= link_to "RECOMMENDATION", new_perfume_path %>
        </li>
        
      
        <li>
        <% if user_signed_in? %>
              <li>
              <%= link_to "Mypage", user_path(current_user.id) %>
              <li>
              <%= button_to 'Logout', destroy_user_session_path, method: :delete %></li>
              </li>
              <% else %>
            <li><%= link_to "Signin", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <header>
   <h1>～<span class="S1">S</span>humiを<span class="S2">S</span>agaして<span class="S3">S</span>hareする<span class="S4">S</span>ite～</h1>

  <link rel="stylesheet" type="text/css" href="css/5-2-4.css">
  <div class="openbtn"><span></span><span></span><span></span></div>
  </header>
  <main>
   <%= yield %>
   </main>
   <footer>
    <p>Copyright © GeekSalon All Rights Reserved.</p>
   </footer>
</body>
  </body> 
</html>
<script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
 <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script>
$(".openbtn").click(function () {
 $(this).toggleClass("active");
 $("#g-nav").toggleClass("panelactive");
});
$("#g-nav a").click(function () {
 $(".openbtn").removeClass("active");
 $("#g-nav").removeClass("panelactive");
});
</script>

app/views/perfumes/index.html.erb
<!DOCTYPE html> <!-- この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head><!--ページに表示されない情報(サイトの裏側の設定)-->
        <meta charset="utf-8">
        <title>香水診断スタート</title><!--ブラウザのタブのタイトルを指定-->
    </head>

   
        
            <h1 class="headline">
            <a>趣味診断</a>
            </h1>
            

        <div class="start">
            <%= button_to new_perfume_path, method: :get do %>
                <p>診断を始める</p>
            <% end %>
        </div>
    

app/views/perfumes/new.html.erb
<body class="perfume_back">
<div class="sindan-all">
<%= form_for(@perfume, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="container-sindan">
        <div class="row">
            <div class="col-12">
                <p>Question1. インドア派？アウトドア派？</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>インドア派～</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>アウトドア派！</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "3", nil %>どっちもある系</p>
            </div>

            <div class="col-12">
                <p>Question2. 生活にもっと刺激が欲しい？</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>欲しい！</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>いらない…</p>
            </div>

            <div class="col-12">
                <p>Question3. 理性と感情どっちを優先しがち？</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>もちろん、理性</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>感情だろ！！</p>
            </div>

            <div class="col-12">
                <p>Question4. 大切にしたいのは…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>論理性だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>情緒だ</p>
            </div>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit "post" %>
    </div>
<% end %>
</div>
</body>

app/views/perfumes/show.html.erb
<div class="intoro">
            <h5>診断結果</h5>
            <p>あなたにおすすめの香りは…</p>
        </div>
        <div class="tweet-container">
            <div class="tweet">
                <% if @perfume.question == "1111" %>
                <h6>レモン</h6>
                <p>柑橘系の代表的な原料</p>
                <p>清涼感があり、爽やかな印象</p>

                <% elsif @perfume.question == "1112" %>
                <h6>シトラス</h6>
                <p>オレンジに似た柑橘系の果物</p>
                <p>リラックス効果がある</p>

                <% elsif @perfume.question == "1121" %>
                <h6>ローズ</h6>
                <p>華やかで上品な香り</p>
                <p>ストレスを緩和してくれる効果がある</p>

                <% elsif @perfume.question == "1122" %>
                <h6>ラベンダー</h6>
                <p>優しく女性らしい香り</p>
                <p>気持ちを落ち着かせてくれる</p>

                <% elsif @perfume.question == "1211" %>
                <h6>ジャスミン</h6>
                <p>爽やかなのに官能的な香り</p>
                <p>幸福感を得やすい</p>

                <% elsif @perfume.question == "1212" %>
                <h6>ピーチ</h6>
                <p>フレッシュで優しい香り</p>
                <p>アンチエイジングにも最適</p>

                <% elsif @perfume.question == "1221" %>
                <h6>アップル</h6>
                <p>特徴的で甘い香り</p>
                <p>万人受けしやすい</p>

                <% elsif @perfume.question == "1222" %>
                <h6>ユーカリ</h6>
                <p>しっかりとした優しい香り</p>
                <p>浄化作用があり。気持ちを落ち着かせてくれる</p>

                <% elsif @perfume.question == "2111" %>
                <h6>ローズマリー</h6>
                <p>きりりとした強めの香りが特徴的</p>
                <p>美容効果が高い</p>

                <% elsif @perfume.question == "2112" %>
                <h6>ベルガモット</h6>
                <p>柑橘系の果実</p>
                <p>甘くてフレッシュな、万能な香料</p>

                <% elsif @perfume.question == "2121" %>
                <h6>ムスク</h6>
                <p>雄のジャコウジカの腹部にある香嚢から抽出した香料</p>
                <p>官能的で重い香り</p>

                <% elsif @perfume.question == "2122" %>
                <h6>アンバー</h6>
                <p>マッコウクジラの結石から抽出した香料</p>
                <p>魅惑的で色気のある香り</p>

                <% elsif @perfume.question == "2211" %>
                <h6>シナモン</h6>
                <p>甘いスパイスの香り</p>
                <p>香水のアクセントとしてよく使われる</p>

                <% elsif @perfume.question == "2212" %>
                <h6>バニラ</h6>
                <p>甘くて官能的な香り</p>
                <p>上品で年齢を問わず人気が高い</p>

                <% elsif @perfume.question == "2221" %>
                <h6>イランイラン</h6>
                <p>色気のある濃厚で甘い香り</p>
                <p>恋愛に効果があり</p>

                <% elsif @perfume.question == "2222" %>
                <h6>サンダルウッド</h6>
                <p>お香としてよく使われる白檀の香り</p>
                <p>集中力を高める効果もあり</p>

                <% end %>

        </div>
        <%= button_to tweets_path, method: :get do %>
            <p>一覧へ戻る</p>
        <% end %>
        <%= button_to perfumes_path, method: :get do %>
            <p>もう一度診断する</p>
        <% end %>

app/views/tweets/anime.html.erb
<body class="anime_back">
<div class="hob-index">
<div class="hobs-container">
 <% @tweets.each do |t| %> 

  <div class="hob-container">
   <div class="hob-images">
     <%= image_tag t.image_url, size: "250x200" if t.image? %><br>
   </div>
      <%= t.about %><br>
      <%= button_to "詳細へ", tweet_path(t.id), method: :get %>
      <%= button_to "編集する", edit_tweet_path(t.id), method: :get %>
      <%= button_to "削除する", tweet_path(t.id), method: :delete %>
  </div>
 <% end %>
</div>
</div>
</body>

app/views/tweets/cooking.html.erb
<body class="cooking_back">
<div class="hob-index">
<div class="hobs-container">
 <% @tweets.each do |t| %> 

  <div class="hob-container">
   <div class="hob-images">
     <%= image_tag t.image_url, size: "250x200" if t.image? %><br>
   </div>
      <%= t.about %><br>
      <%= button_to "詳細へ", tweet_path(t.id), method: :get %>
      <%= button_to "編集する", edit_tweet_path(t.id), method: :get %>
      <%= button_to "削除する", tweet_path(t.id), method: :delete %>
  </div>
 <% end %>
</div>
</div>

</body>

app/views/tweets/edit.html.erb
<div class="edit">
<%= form_for @tweet do |f| %>
    <%= f.label :about %>
    <%= f.text_field :about, :size => 140 %> 
    <%= f.submit "編集する" %>
<% end %>
</div>

app/views/tweets/index.html.erb
<body class="index_back">
<div class="L">
<%= link_to tweets_result_path do %>
  <%= image_tag 'sports_link2.jpg', class:"logo-image1" %>
<% end %>
<%= link_to tweets_music_path do %>
  <%= image_tag 'music_link2.jpg', class:"logo-image2" %>
<% end %>
<%= link_to tweets_cooking_path do %>
  <%= image_tag 'cooking_link2.jpg', class:"logo-image3" %>
<% end %>
<%= link_to tweets_anime_path do %>
  <%= image_tag 'anime_link2.jpg', class:"logo-image4" %>
<% end %>
<%= stylesheet_link_tag 'index', :media => "all" %>
</div>
</body>

app/views/tweets/music.html.erb
<body class="music_back">

<div class="hob-index">
<div class="hobs-container">
 <% @tweets.each do |t| %>

  <div class="hob-container">
   <div class="hob-images">
     <%= image_tag t.image_url, size: "250x200" if t.image? %><br>
   </div>
      <%= t.about %><br>
      <%= button_to "詳細へ", tweet_path(t.id), method: :get %>
      <%= button_to "編集する", edit_tweet_path(t.id), method: :get %>
      <%= button_to "削除する", tweet_path(t.id), method: :delete %>
  </div>
 <% end %>
</div>
</div>

</body>

app/views/tweets/new.html.erb
<body class="sinkitoukou-back">
<div class="toukou">
<%= form_for @tweet do |f| %>

    <div class="field">
    <%= f.label :投稿フォーム  %></br>
    <%= f.text_area :about, :size => "30x2" %>
    </div>

  <div class="field">
    <%= f.label :項目名  %><br>
    <%= f.select :genre, 
    [["スポーツ", "スポーツ"], 
    ["音楽", "音楽"], 
    ["料理", "料理"],
    ["漫画・アニメ", "漫画・アニメ"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :ギャラリー %></br>
    <%= f.file_field :image %>
  </div>

    <!-- 
    <div class='field'>
      
      <p>タグ</p>
          <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
              <div class='form-check'>
                  <%= tag.label class: 'form-check-label' do %>
                      <%= tag.check_box class: 'form-check-input' %>
                      <%= tag.text %>
                  <% end %>
              </div>
          <% end %>
      </div> 
      -->
    <div class="field2">
      <%= f.submit "投稿する" %>
    </div>                
<% end %>


<%= stylesheet_link_tag 'new', :media => "all" %>
</div>
</body>

app/views/tweets/result.html.erb
<body class="sports_back">
<div class="hob-index">
<div class="hobs-container">
 <% @tweets.each do |t| %> 

  <div class="hob-container">
   <div class="hob-images">
     <%= image_tag t.image_url, size: "250x200" if t.image? %><br>
   </div>
      <%= t.about %><br>
      <%= button_to "詳細へ", tweet_path(t.id), method: :get %>
      <%= button_to "編集する", edit_tweet_path(t.id), method: :get %>
      <%= button_to "削除する", tweet_path(t.id), method: :delete %>
  </div>
 <% end %>
</div>
</div>

</body>

app/views/tweets/show.html.erb
<body class="shousai_back">
<h1>投稿詳細</h1>

<div class="tweet">
<div class="hob-images">
     <%= image_tag @tweet.image_url, size: "250x200" if @tweet.image? %><br>
  </div>
  <p><%= @tweet.about %></p>
<a href="javascript:void(0)" onclick="window.history.back();">前のページに戻る</a>
</div>
</body>

app/views/tweets/sports.html.erb
<% @tweets.each do |t| %>
    <%= t.about %>
    <%= link_to "詳細へ", tweet_path(t.id) %>
<% end %>

app/views/tweets/sports_index.html.erb
<% @tweets.each do |t| %>
 
    <%= t.about %>
        
    
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>MyPage</h1>
<p>name : <%= @user.name %></p>
<p>email : <%= @user.email %></p>
<p>profile : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.about %>
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.about %>
<% end %>
<!-- ここまで-->